// SLOW-MODE (remove later)
/* eslint-disable react-refresh/only-export-components */ // SLOW-MODE (remove later)
import axios from "axios"; // SLOW-MODE (remove later)
import { useEffect, useState } from "react"; // SLOW-MODE (remove later)
import { Link, useNavigate } from "react-router-dom"; // SLOW-MODE (remove later)

// SLOW-MODE (remove later)
const BASE_DELAY_MS = Number(import.meta.env.VITE_SLOW_DELAY_MS) || 6000; // SLOW-MODE (remove later)
const ACTION_DELAYS_MS = { // SLOW-MODE (remove later)
  resort: Number(import.meta.env.VITE_RESORT_NAV_DELAY_MS) || 14000, // SLOW-MODE (remove later)
  search: Number(import.meta.env.VITE_SEARCH_DELAY_MS) || 14000, // SLOW-MODE (remove later)
}; // SLOW-MODE (remove later)
const isAllowedEnvironment = // SLOW-MODE (remove later)
  import.meta.env.VERCEL_ENV !== "production" && // SLOW-MODE (remove later)
  (import.meta.env.MODE === "development" || // SLOW-MODE (remove later)
    import.meta.env.VERCEL_ENV === "preview" || // SLOW-MODE (remove later)
    import.meta.env.VITE_APP_ENV === "staging"); // SLOW-MODE (remove later)
const slowModeEnabled = // SLOW-MODE (remove later)
  import.meta.env.VITE_SLOW_MODE === "true" && isAllowedEnvironment; // SLOW-MODE (remove later)
const BYPASS_KEY = "dev_bypass"; // SLOW-MODE (remove later)
const PROGRESSIVE_KEY = "slow_mode_api_calls"; // SLOW-MODE (remove later)
const LOADING_EVENT = "slow-mode-loading"; // SLOW-MODE (remove later)
let activeDelays = 0; // SLOW-MODE (remove later)
let interceptorsInstalled = false; // SLOW-MODE (remove later)
let initialDelayPromise; // SLOW-MODE (remove later)

// SLOW-MODE (remove later)
function isBypassed() { // SLOW-MODE (remove later)
  return window.localStorage.getItem(BYPASS_KEY) === "true"; // SLOW-MODE (remove later)
} // SLOW-MODE (remove later)

// SLOW-MODE (remove later)
function applyBypassQuery() { // SLOW-MODE (remove later)
  const url = new URL(window.location.href); // SLOW-MODE (remove later)
  const devAction = url.searchParams.get("dev"); // SLOW-MODE (remove later)
  if (devAction !== "on" && devAction !== "off") return; // SLOW-MODE (remove later)
  if (devAction === "on") { // SLOW-MODE (remove later)
    window.localStorage.setItem(BYPASS_KEY, "true"); // SLOW-MODE (remove later)
  } else { // SLOW-MODE (remove later)
    window.localStorage.removeItem(BYPASS_KEY); // SLOW-MODE (remove later)
  } // SLOW-MODE (remove later)
  url.searchParams.delete("dev"); // SLOW-MODE (remove later)
  window.history.replaceState({}, "", url); // SLOW-MODE (remove later)
} // SLOW-MODE (remove later)

// SLOW-MODE (remove later)
export const isSlowModeEnabled = () => slowModeEnabled; // SLOW-MODE (remove later)
export const isSlowModeBypassed = () => !slowModeEnabled || isBypassed(); // SLOW-MODE (remove later)

// SLOW-MODE (remove later)
export function sleep(ms) { // SLOW-MODE (remove later)
  return new Promise((resolve) => window.setTimeout(resolve, ms)); // SLOW-MODE (remove later)
} // SLOW-MODE (remove later)

// SLOW-MODE (remove later)
export async function slowDown({ progressive = false } = {}) { // SLOW-MODE (remove later)
  if (!slowModeEnabled || isBypassed()) return; // SLOW-MODE (remove later)

  let progressiveDelay = BASE_DELAY_MS; // SLOW-MODE (remove later)
  if (progressive) { // SLOW-MODE (remove later)
    const apiCallCount = Number(window.sessionStorage.getItem(PROGRESSIVE_KEY) || 0) + 1; // SLOW-MODE (remove later)
    window.sessionStorage.setItem(PROGRESSIVE_KEY, String(apiCallCount)); // SLOW-MODE (remove later)
    progressiveDelay = Math.min(BASE_DELAY_MS * (1 + apiCallCount * 0.1), BASE_DELAY_MS * 3); // SLOW-MODE (remove later)
  } // SLOW-MODE (remove later)

  const jitter = progressiveDelay * (Math.random() * 0.6 - 0.3); // SLOW-MODE (remove later)
  const delay = Math.min(BASE_DELAY_MS * 3, Math.max(0, progressiveDelay + jitter)); // SLOW-MODE (remove later)
  activeDelays += 1; // SLOW-MODE (remove later)
  window.dispatchEvent(new CustomEvent(LOADING_EVENT, { detail: activeDelays })); // SLOW-MODE (remove later)
  try { // SLOW-MODE (remove later)
    await sleep(delay); // SLOW-MODE (remove later)
  } finally { // SLOW-MODE (remove later)
    activeDelays -= 1; // SLOW-MODE (remove later)
    window.dispatchEvent(new CustomEvent(LOADING_EVENT, { detail: activeDelays })); // SLOW-MODE (remove later)
  } // SLOW-MODE (remove later)
} // SLOW-MODE (remove later)

// SLOW-MODE (remove later)
export async function delaySlowModeAction(action) { // SLOW-MODE (remove later)
  if (!slowModeEnabled || isBypassed()) return; // SLOW-MODE (remove later)
  const delay = ACTION_DELAYS_MS[action]; // SLOW-MODE (remove later)
  if (!Number.isFinite(delay) || delay <= 0) return; // SLOW-MODE (remove later)

  activeDelays += 1; // SLOW-MODE (remove later)
  window.dispatchEvent(new CustomEvent(LOADING_EVENT, { detail: activeDelays })); // SLOW-MODE (remove later)
  try { // SLOW-MODE (remove later)
    await sleep(delay); // SLOW-MODE (remove later)
  } finally { // SLOW-MODE (remove later)
    activeDelays -= 1; // SLOW-MODE (remove later)
    window.dispatchEvent(new CustomEvent(LOADING_EVENT, { detail: activeDelays })); // SLOW-MODE (remove later)
  } // SLOW-MODE (remove later)
} // SLOW-MODE (remove later)

// SLOW-MODE (remove later)
export function runSlowModeAction(action, callback) { // SLOW-MODE (remove later)
  if (!slowModeEnabled || isBypassed()) return callback(); // SLOW-MODE (remove later)
  return delaySlowModeAction(action).then(callback); // SLOW-MODE (remove later)
} // SLOW-MODE (remove later)

// SLOW-MODE (remove later)
export function SlowModeLink({ to, action, state, replace, children, onClick, ...rest }) { // SLOW-MODE (remove later)
  const navigate = useNavigate(); // SLOW-MODE (remove later)

  const handleClick = async (event) => { // SLOW-MODE (remove later)
    onClick?.(event); // SLOW-MODE (remove later)
    if (event.defaultPrevented || event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey || rest.target === "_blank") return; // SLOW-MODE (remove later)
    if (!slowModeEnabled || isBypassed()) return; // SLOW-MODE (remove later)
    event.preventDefault(); // SLOW-MODE (remove later)
    await delaySlowModeAction(action); // SLOW-MODE (remove later)
    navigate(to, { state, replace }); // SLOW-MODE (remove later)
  }; // SLOW-MODE (remove later)

  return <Link to={to} state={state} replace={replace} onClick={handleClick} {...rest}>{children}</Link>; // SLOW-MODE (remove later)
} // SLOW-MODE (remove later)

// SLOW-MODE (remove later)
function delayInitialLoad() { // SLOW-MODE (remove later)
  initialDelayPromise ||= slowDown(); // SLOW-MODE (remove later)
  return initialDelayPromise; // SLOW-MODE (remove later)
} // SLOW-MODE (remove later)

// SLOW-MODE (remove later)
export function initializeSlowMode() { // SLOW-MODE (remove later)
  if (!isAllowedEnvironment) return; // SLOW-MODE (remove later)
  applyBypassQuery(); // SLOW-MODE (remove later)
  if (!slowModeEnabled || interceptorsInstalled) return; // SLOW-MODE (remove later)
  interceptorsInstalled = true; // SLOW-MODE (remove later)

  const originalFetch = window.fetch.bind(window); // SLOW-MODE (remove later)
  window.fetch = async (...args) => { // SLOW-MODE (remove later)
    const response = await originalFetch(...args); // SLOW-MODE (remove later)
    await slowDown({ progressive: true }); // SLOW-MODE (remove later)
    return response; // SLOW-MODE (remove later)
  }; // SLOW-MODE (remove later)

  axios.interceptors.response.use( // SLOW-MODE (remove later)
    async (response) => { // SLOW-MODE (remove later)
      await slowDown({ progressive: true }); // SLOW-MODE (remove later)
      return response; // SLOW-MODE (remove later)
    }, // SLOW-MODE (remove later)
    async (error) => { // SLOW-MODE (remove later)
      await slowDown({ progressive: true }); // SLOW-MODE (remove later)
      return Promise.reject(error); // SLOW-MODE (remove later)
    }, // SLOW-MODE (remove later)
  ); // SLOW-MODE (remove later)
} // SLOW-MODE (remove later)

// SLOW-MODE (remove later)
function SlowModeSpinner({ overlay = false }) { // SLOW-MODE (remove later)
  return ( // SLOW-MODE (remove later)
    <div className={`${overlay ? "fixed inset-0 z-[9999]" : "min-h-screen"} flex flex-col items-center justify-center gap-4 bg-white`}> {/* SLOW-MODE (remove later) */}
      <span className="loading loading-spinner loading-lg text-primary" aria-hidden="true" /> {/* SLOW-MODE (remove later) */}
      <p>Loading...</p> {/* SLOW-MODE (remove later) */}
    </div> // SLOW-MODE (remove later)
  ); // SLOW-MODE (remove later)
} // SLOW-MODE (remove later)

// SLOW-MODE (remove later)
export function SlowModeProvider({ children }) { // SLOW-MODE (remove later)
  if (!slowModeEnabled) return children; // SLOW-MODE (remove later)
  return <EnabledSlowModeProvider>{children}</EnabledSlowModeProvider>; // SLOW-MODE (remove later)
} // SLOW-MODE (remove later)

// SLOW-MODE (remove later)
function EnabledSlowModeProvider({ children }) { // SLOW-MODE (remove later)
  const [initialLoadComplete, setInitialLoadComplete] = useState(isSlowModeBypassed()); // SLOW-MODE (remove later)
  const [showLoading, setShowLoading] = useState(false); // SLOW-MODE (remove later)

  useEffect(() => { // SLOW-MODE (remove later)
    if (isSlowModeBypassed()) return undefined; // SLOW-MODE (remove later)

    let mounted = true; // SLOW-MODE (remove later)
    const handleLoading = (event) => setShowLoading(event.detail > 0); // SLOW-MODE (remove later)
    window.addEventListener(LOADING_EVENT, handleLoading); // SLOW-MODE (remove later)
    delayInitialLoad().finally(() => { // SLOW-MODE (remove later)
      if (mounted) setInitialLoadComplete(true); // SLOW-MODE (remove later)
    }); // SLOW-MODE (remove later)

    return () => { // SLOW-MODE (remove later)
      mounted = false; // SLOW-MODE (remove later)
      window.removeEventListener(LOADING_EVENT, handleLoading); // SLOW-MODE (remove later)
    }; // SLOW-MODE (remove later)
  }, []); // SLOW-MODE (remove later)

  if (isSlowModeBypassed()) return children; // SLOW-MODE (remove later)
  if (!initialLoadComplete) return <SlowModeSpinner />; // SLOW-MODE (remove later)

  return ( // SLOW-MODE (remove later)
    <> {/* SLOW-MODE (remove later) */}
      {children} {/* SLOW-MODE (remove later) */}
      {showLoading && <SlowModeSpinner overlay />} {/* SLOW-MODE (remove later) */}
    </> // SLOW-MODE (remove later)
  ); // SLOW-MODE (remove later)
} // SLOW-MODE (remove later)
